# Generated by Django 3.2.12 on 2022-02-10 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=2000)),
                ('release_date', models.DateField()),
                ('developer', models.CharField(max_length=50)),
                ('storage_req', models.CharField(max_length=20)),
                ('trailer', models.CharField(max_length=150)),
                ('cover', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('Action', 'Action'), ('Action-Adventure', 'Action-Adventure'), ('Adventure', 'Adventure'), ('Role-Playing', 'Role-Playing'), ('Simulation', 'Simulation'), ('Strategy', 'Strategy'), ('Sports', 'Sports'), ('Puzzle', 'Puzzle'), ('Indie', 'Indie'), ('MMORPG', 'MMORPG - Massive Multiplayer Online RPG'), ('MOBA', 'MOBA - Multiplayer Online Battle Arena'), ('Shooter', 'Shooter'), ('Stealth', 'Stealth'), ('Survival', 'Survival')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('PS', 'PlayStation'), ('PS2', 'PlayStation 2'), ('PS3', 'PlayStation 3'), ('PS4', 'PlayStation 4'), ('PS5', 'PlayStation 5'), ('Xbox', 'Xbox'), ('X360', 'Xbox 360'), ('XB1', 'Xbox One'), ('XS S/X', 'Xbox Series S/X'), ('GB', 'Nintendo Gameboy'), ('DS', 'Nintendo DS'), ('3DS', 'Nintendo 3DS'), ('N64', 'Nintedo 64'), ('GC', 'Nintendo GameCube'), ('WII', 'Nintendo Wii'), ('WIIU', 'Nintendo Wii U'), ('SWITCH', 'Nintendo Switch'), ('PC', 'PC'), ('OCULUS', 'Oculus VR'), ('GENESIS', 'Sega Genesis'), ('DREAMCAST', 'Sega Dreamcast')], max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=300)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='gamr.game')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='gamr.user')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='genres',
            field=models.ManyToManyField(to='gamr.Genre'),
        ),
        migrations.AddField(
            model_name='game',
            name='platforms',
            field=models.ManyToManyField(to='gamr.Platform'),
        ),
        migrations.AddField(
            model_name='game',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='gamr.user'),
        ),
    ]
