# Generated by Django 3.2.12 on 2022-02-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='genres',
            field=models.ManyToManyField(to='gamr.Genre'),
        ),
    ]
