# Generated by Django 3.2.12 on 2022-02-07 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='games',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='genres',
        ),
    ]
