# Generated by Django 3.2.12 on 2022-02-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamr', '0002_auto_20220207_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
