# Generated by Django 3.2.12 on 2022-02-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamr', '0003_alter_game_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(max_length=2000),
        ),
    ]
